version: '3'
services:
  meinedb:
    image: postgres:latest
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test123
  bons1:
    build: .
    ports:
      - "8080:8080"
      - "8001:8001"
    depends_on:
      - meinedb
    environment:
      - "JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8001,server=y,suspend=n"
  bons2:
    build: .
    ports:
      - "8081:8080"
      - "8002:8001"
    depends_on:
      - meinedb
    environment:
      - "JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8001,server=y,suspend=n"
  aws_mock:
    image: "rodolpheche/wiremock:latest"
    command: ["--verbose"] # "--global-response-templating "--verbose"" "--record-mappings",
    ports:
      - "8083:8080"
      - "8443:8443"
