version: '3'
services:
  meinedb:
    image: postgres:latest
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test123
  bons1:
    build: .
    ports:
      - "8080:8080"
      - "8001:8001"
    depends_on:
      - meinedb
  bons2:
    build: .
    ports:
      - "8081:8080"
      - "8002:8001"
    depends_on:
      - meinedb
  aws_mock:
    image: "rodolpheche/wiremock:latest"
    command: ["--record-mappings","--verbose"] # "--global-response-templating "--verbose""
    ports:
      - "8083:8080"
      - "8443:8443"
