spring:
  data:
    rest:
      basePath: /api
security:
  ignored: "/**"
  basic:
    enabled: false
management:
  security:
    enabled: false
logging:
  level:
    root: INFO
    org:
      hibernate: INFO


